[project]
name = "auckland-transport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.13.2",
    "pydantic>=2.0.0",
    "requests>=2.31.0",
]
